### ISSUE TITLE
sql error when using [bloghubTags] component

### ISSUE THREAD

**Issue by alexwenzel** [RatMD/bloghub-plugin#10]
hello,

i got an error when using your [bloghubTags] component:

![image](https://user-images.githubusercontent.com/3659928/228392047-e499cdea-c797-48df-b906-25bfeb64f9cb.png)

I think, this is because some columns are not correct added during migration.
When i remove the lines 97 and 98 inside `plugins/ratmd/bloghub/components/Tags.php`, everything works for me.

I installed your plugin `1.3.8`.

all the best

**Comment by tecnotrade** [comment]
Just replace "where" with "having" and everything will work correctly ;)

**Comment by alexwenzel** [comment]
can i do a PR?

**Comment by tecnotrade** [comment]
Why not? ;)

**Comment by alexwenzel** [comment]
fixed in #13

**Comment by SamBrishes** [comment]
Many thanks for the contribution (again). Sorry for the long delay. 

The new update will be pushed to the oc repository today.
