### ISSUE TITLE
WinterCMS Port?

### ISSUE THREAD

**Issue by SamBrishes** [RatMD/bloghub-plugin#3]
Check if a WinterCMS port is possible with just a little effort.

Related:
https://github.com/RatMD/newshub-theme/issues/3

**Comment by spanjaan** [comment]
Hi
@SamBrishes 
Greetings.
I used this plugin in octobercms, very advanced and works well.
If this plugin can be used in wintercms, it would be great. If it can be used in wintercms after a bit of work, I strongly urge you to make it.

thank you.

**Comment by SamBrishes** [comment]
Seems like someone already did a WinterCMS fork of my bloghub plugin. Probably the best (and only) solution at the moment.

-> https://github.com/for-wintercms/wn-bloghub-plugin
