### ISSUE TITLE
Wrong columns type

### ISSUE THREAD

**Issue by naynyeinchan** [RatMD/bloghub-plugin#6]
column 'author_table' in table 'ratmd_bloghub_comments' need to be string to work properly

'$table->string('author_table')->nullable();'

**Comment by SamBrishes** [comment]
Hello,

thanks for your bug report. I fixed it in the current master branch, I'll push a new version today or tomorrow.

~Sam.

**Comment by SamBrishes** [comment]
Fixed in v1.3.3 (Version has been pushed to Octobers Marketplace).
