### ISSUE TITLE
Tos not working

### ISSUE THREAD

**Issue by naynyeinchan** [RatMD/bloghub-plugin#7]
$this->page['showCommentFormTos'] = $this->config('form_tos_checkbox') === '0';

'0' need to be '1' to get right condition

**Comment by SamBrishes** [comment]
Hello,

thanks again for your bug report. I fixed it in the current master branch, I'll push a new version today or tomorrow.

~Sam.

**Comment by SamBrishes** [comment]
Fixed in v1.3.3 (Version has been pushed to Octobers Marketplace).
